name: MaceList
version: '1.0'
main: me.juusk.maceList.MaceList
api-version: '1.21'
authors: [ JuusK ]
depend: [NBTAPI]
softdepend: [PlaceholderAPI]
description: Lists all players with maces.

commands:
  macelist:
    description: Lists all players who have a mace
    aliases: [whohasmace, maces]
  purgemaces:
    description: Purges maces from inactive players
    permission: macelist.purge


